name: name_avatar
description: The NameAvatar widget in Flutter is a versatile widget designed to showcase a circular avatar along with text representing a name. It serves as a convenient tool for showcasing user avatars across different applications.
version: 0.0.1
homepage: https://github.com/dipta-2707/name_avatar
repository: https://github.com/dipta-2707/name_avatar

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
